import {
  type CriminalProfile,
  type DetectionLog,
  DetectionType,
  type MissingPerson,
  ThreatLevel,
} from "../backend";

export const mockCriminals: CriminalProfile[] = [
  {
    id: "c001",
    name: "Viktor Drazen",
    age: 42n,
    gender: "Male",
    nationality: "Serbian",
    criminalRecord:
      "Armed robbery (2015), Assault with deadly weapon (2018), Drug trafficking (2021). Known to carry firearms. Escaped federal custody in 2022.",
    threatLevel: ThreatLevel.critical,
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=viktor&backgroundColor=b6e3f4",
    aliases: ["The Ghost", "Viktor Black"],
    isActive: true,
    createdAt: BigInt(Date.now() - 1000000),
  },
  {
    id: "c002",
    name: "Marcus Thorn",
    age: 35n,
    gender: "Male",
    nationality: "American",
    criminalRecord:
      "Grand theft auto (2016), Money laundering (2019), Identity fraud (2022).",
    threatLevel: ThreatLevel.high,
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=c0aede",
    aliases: ["Digital Ghost"],
    isActive: true,
    createdAt: BigInt(Date.now() - 2000000),
  },
  {
    id: "c003",
    name: "Elena Vasquez",
    age: 29n,
    gender: "Female",
    nationality: "Colombian",
    criminalRecord: "Drug smuggling (2020), Conspiracy to commit fraud (2022).",
    threatLevel: ThreatLevel.medium,
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=elena&backgroundColor=ffd5dc",
    aliases: ["La Serpiente"],
    isActive: true,
    createdAt: BigInt(Date.now() - 3000000),
  },
  {
    id: "c004",
    name: "Jin-ho Park",
    age: 51n,
    gender: "Male",
    nationality: "South Korean",
    criminalRecord: "Cybercrime (2017), Corporate espionage (2020).",
    threatLevel: ThreatLevel.high,
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=jinho&backgroundColor=b6e3f4",
    aliases: ["Shadow Net"],
    isActive: true,
    createdAt: BigInt(Date.now() - 4000000),
  },
  {
    id: "c005",
    name: "Alexei Morozov",
    age: 38n,
    gender: "Male",
    nationality: "Russian",
    criminalRecord:
      "Arms dealing (2019), Aggravated assault (2021), Weapons possession.",
    threatLevel: ThreatLevel.critical,
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=alexei&backgroundColor=d1d4f9",
    aliases: ["The Bear", "Morozov"],
    isActive: true,
    createdAt: BigInt(Date.now() - 5000000),
  },
];

export const mockMissingPersons: MissingPerson[] = [
  {
    id: "m001",
    name: "Sarah Chen",
    ageAtDisappearance: 24n,
    dateOfDisappearance: BigInt(Date.now() - 365 * 24 * 60 * 60 * 1000 * 2),
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah&backgroundColor=ffd5dc",
    description:
      "Last seen near downtown bus station. Wearing blue jacket and jeans. 5ft 4in, brown hair.",
    reportedBy: "Family member",
    isFound: false,
    createdAt: BigInt(Date.now() - 365 * 24 * 60 * 60 * 1000 * 2),
  },
  {
    id: "m002",
    name: "David Osei",
    ageAtDisappearance: 16n,
    dateOfDisappearance: BigInt(Date.now() - 365 * 24 * 60 * 60 * 1000 * 5),
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=david&backgroundColor=b6e3f4",
    description:
      "Missing since school field trip. Last seen near city park. 5ft 8in, wearing school uniform.",
    reportedBy: "School authority",
    isFound: false,
    createdAt: BigInt(Date.now() - 365 * 24 * 60 * 60 * 1000 * 5),
  },
  {
    id: "m003",
    name: "Rosa Morales",
    ageAtDisappearance: 45n,
    dateOfDisappearance: BigInt(Date.now() - 365 * 24 * 60 * 60 * 1000 * 1),
    photoUrl:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=rosa&backgroundColor=c0aede",
    description:
      "Missing after leaving workplace. Vehicle found abandoned. Possible foul play.",
    reportedBy: "Husband",
    isFound: false,
    createdAt: BigInt(Date.now() - 365 * 24 * 60 * 60 * 1000 * 1),
  },
];

export const mockDetectionLogs: DetectionLog[] = [
  {
    id: "l001",
    timestamp: BigInt(Date.now() - 60000),
    detectedPersonName: "Viktor Drazen",
    matchPercentage: 94n,
    threatLevel: ThreatLevel.critical,
    detectionType: DetectionType.knownCriminal,
    activityLabel: "aggressive",
    weaponsDetected: ["firearm"],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-01",
    location: "Main Entrance",
  },
  {
    id: "l002",
    timestamp: BigInt(Date.now() - 300000),
    detectedPersonName: "Unknown Subject #47",
    matchPercentage: 0n,
    threatLevel: ThreatLevel.medium,
    detectionType: DetectionType.unknownPerson,
    activityLabel: "suspicious",
    weaponsDetected: [],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-03",
    location: "Parking Lot B",
  },
  {
    id: "l003",
    timestamp: BigInt(Date.now() - 600000),
    detectedPersonName: "Marcus Thorn",
    matchPercentage: 87n,
    threatLevel: ThreatLevel.high,
    detectionType: DetectionType.knownCriminal,
    activityLabel: "normal",
    weaponsDetected: [],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-02",
    location: "Side Exit",
  },
  {
    id: "l004",
    timestamp: BigInt(Date.now() - 1200000),
    detectedPersonName: "Sarah Chen",
    matchPercentage: 91n,
    threatLevel: ThreatLevel.low,
    detectionType: DetectionType.missingPerson,
    activityLabel: "normal",
    weaponsDetected: [],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-04",
    location: "Shopping Mall North",
  },
  {
    id: "l005",
    timestamp: BigInt(Date.now() - 1800000),
    detectedPersonName: "Unknown Subject #51",
    matchPercentage: 0n,
    threatLevel: ThreatLevel.high,
    detectionType: DetectionType.unknownPerson,
    activityLabel: "fighting",
    weaponsDetected: ["knife"],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-01",
    location: "Main Entrance",
  },
  {
    id: "l006",
    timestamp: BigInt(Date.now() - 3600000),
    detectedPersonName: "Alexei Morozov",
    matchPercentage: 89n,
    threatLevel: ThreatLevel.critical,
    detectionType: DetectionType.knownCriminal,
    activityLabel: "aggressive",
    weaponsDetected: ["firearm", "knife"],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-05",
    location: "Rooftop",
  },
  {
    id: "l007",
    timestamp: BigInt(Date.now() - 7200000),
    detectedPersonName: "Elena Vasquez",
    matchPercentage: 82n,
    threatLevel: ThreatLevel.medium,
    detectionType: DetectionType.knownCriminal,
    activityLabel: "suspicious",
    weaponsDetected: [],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-02",
    location: "Side Exit",
  },
  {
    id: "l008",
    timestamp: BigInt(Date.now() - 14400000),
    detectedPersonName: "Unknown Subject #33",
    matchPercentage: 0n,
    threatLevel: ThreatLevel.low,
    detectionType: DetectionType.unknownPerson,
    activityLabel: "normal",
    weaponsDetected: [],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-03",
    location: "Parking Lot B",
  },
  {
    id: "l009",
    timestamp: BigInt(Date.now() - 21600000),
    detectedPersonName: "Jin-ho Park",
    matchPercentage: 76n,
    threatLevel: ThreatLevel.high,
    detectionType: DetectionType.knownCriminal,
    activityLabel: "suspicious",
    weaponsDetected: [],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-06",
    location: "Server Room",
  },
  {
    id: "l010",
    timestamp: BigInt(Date.now() - 43200000),
    detectedPersonName: "David Osei",
    matchPercentage: 88n,
    threatLevel: ThreatLevel.low,
    detectionType: DetectionType.missingPerson,
    activityLabel: "normal",
    weaponsDetected: [],
    evidencePhotoUrl: undefined,
    cameraId: "CAM-04",
    location: "Shopping Mall North",
  },
];
