/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CriminalProfile {
  'id' : string,
  'age' : bigint,
  'criminalRecord' : string,
  'threatLevel' : ThreatLevel,
  'name' : string,
  'createdAt' : Timestamp,
  'photoUrl' : string,
  'nationality' : string,
  'isActive' : boolean,
  'gender' : string,
  'aliases' : Array<string>,
}
export interface DetectionLog {
  'id' : string,
  'activityLabel' : string,
  'threatLevel' : ThreatLevel,
  'detectedPersonName' : string,
  'matchPercentage' : bigint,
  'evidencePhotoUrl' : [] | [string],
  'timestamp' : Timestamp,
  'location' : string,
  'weaponsDetected' : Array<string>,
  'cameraId' : string,
  'detectionType' : DetectionType,
}
export type DetectionType = { 'missingPerson' : null } |
  { 'knownCriminal' : null } |
  { 'unknownPerson' : null };
export interface EvidenceRecord {
  'id' : string,
  'metadata' : string,
  'timestamp' : Timestamp,
  'blobId' : string,
  'detectionLogId' : string,
}
export interface MissingPerson {
  'id' : string,
  'dateOfDisappearance' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'photoUrl' : string,
  'reportedBy' : string,
  'isFound' : boolean,
  'ageAtDisappearance' : bigint,
}
export interface SystemStats {
  'missingPersonsCount' : bigint,
  'totalCriminals' : bigint,
  'detectionsToday' : bigint,
  'activeAlerts' : bigint,
}
export type ThreatLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCriminalProfile' : ActorMethod<[CriminalProfile], undefined>,
  'addDetectionLog' : ActorMethod<[DetectionLog], undefined>,
  'addEvidenceRecord' : ActorMethod<[EvidenceRecord], undefined>,
  'addMissingPerson' : ActorMethod<[MissingPerson], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCriminalProfile' : ActorMethod<[string], undefined>,
  'deleteMissingPerson' : ActorMethod<[string], undefined>,
  'getAllCriminalProfiles' : ActorMethod<[], Array<CriminalProfile>>,
  'getAllDetectionLogs' : ActorMethod<[], Array<DetectionLog>>,
  'getAllEvidenceRecords' : ActorMethod<[], Array<EvidenceRecord>>,
  'getAllMissingPersons' : ActorMethod<[], Array<MissingPerson>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCriminalProfile' : ActorMethod<[string], [] | [CriminalProfile]>,
  'getEvidenceRecord' : ActorMethod<[string], [] | [EvidenceRecord]>,
  'getMissingPerson' : ActorMethod<[string], [] | [MissingPerson]>,
  'getSystemStats' : ActorMethod<[], SystemStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCriminalProfile' : ActorMethod<[CriminalProfile], undefined>,
  'updateMissingPerson' : ActorMethod<[MissingPerson], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
