/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ThreatLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CriminalProfile = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'criminalRecord' : IDL.Text,
  'threatLevel' : ThreatLevel,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'photoUrl' : IDL.Text,
  'nationality' : IDL.Text,
  'isActive' : IDL.Bool,
  'gender' : IDL.Text,
  'aliases' : IDL.Vec(IDL.Text),
});
export const DetectionType = IDL.Variant({
  'missingPerson' : IDL.Null,
  'knownCriminal' : IDL.Null,
  'unknownPerson' : IDL.Null,
});
export const DetectionLog = IDL.Record({
  'id' : IDL.Text,
  'activityLabel' : IDL.Text,
  'threatLevel' : ThreatLevel,
  'detectedPersonName' : IDL.Text,
  'matchPercentage' : IDL.Nat,
  'evidencePhotoUrl' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'location' : IDL.Text,
  'weaponsDetected' : IDL.Vec(IDL.Text),
  'cameraId' : IDL.Text,
  'detectionType' : DetectionType,
});
export const EvidenceRecord = IDL.Record({
  'id' : IDL.Text,
  'metadata' : IDL.Text,
  'timestamp' : Timestamp,
  'blobId' : IDL.Text,
  'detectionLogId' : IDL.Text,
});
export const MissingPerson = IDL.Record({
  'id' : IDL.Text,
  'dateOfDisappearance' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'reportedBy' : IDL.Text,
  'isFound' : IDL.Bool,
  'ageAtDisappearance' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SystemStats = IDL.Record({
  'missingPersonsCount' : IDL.Nat,
  'totalCriminals' : IDL.Nat,
  'detectionsToday' : IDL.Nat,
  'activeAlerts' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCriminalProfile' : IDL.Func([CriminalProfile], [], []),
  'addDetectionLog' : IDL.Func([DetectionLog], [], []),
  'addEvidenceRecord' : IDL.Func([EvidenceRecord], [], []),
  'addMissingPerson' : IDL.Func([MissingPerson], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCriminalProfiles' : IDL.Func(
      [],
      [IDL.Vec(CriminalProfile)],
      ['query'],
    ),
  'getAllDetectionLogs' : IDL.Func([], [IDL.Vec(DetectionLog)], ['query']),
  'getAllEvidenceRecords' : IDL.Func([], [IDL.Vec(EvidenceRecord)], ['query']),
  'getAllMissingPersons' : IDL.Func([], [IDL.Vec(MissingPerson)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCriminalProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CriminalProfile)],
      ['query'],
    ),
  'getEvidenceRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EvidenceRecord)],
      ['query'],
    ),
  'getMissingPerson' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MissingPerson)],
      ['query'],
    ),
  'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCriminalProfile' : IDL.Func([CriminalProfile], [], []),
  'updateMissingPerson' : IDL.Func([MissingPerson], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ThreatLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CriminalProfile = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'criminalRecord' : IDL.Text,
    'threatLevel' : ThreatLevel,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'photoUrl' : IDL.Text,
    'nationality' : IDL.Text,
    'isActive' : IDL.Bool,
    'gender' : IDL.Text,
    'aliases' : IDL.Vec(IDL.Text),
  });
  const DetectionType = IDL.Variant({
    'missingPerson' : IDL.Null,
    'knownCriminal' : IDL.Null,
    'unknownPerson' : IDL.Null,
  });
  const DetectionLog = IDL.Record({
    'id' : IDL.Text,
    'activityLabel' : IDL.Text,
    'threatLevel' : ThreatLevel,
    'detectedPersonName' : IDL.Text,
    'matchPercentage' : IDL.Nat,
    'evidencePhotoUrl' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'location' : IDL.Text,
    'weaponsDetected' : IDL.Vec(IDL.Text),
    'cameraId' : IDL.Text,
    'detectionType' : DetectionType,
  });
  const EvidenceRecord = IDL.Record({
    'id' : IDL.Text,
    'metadata' : IDL.Text,
    'timestamp' : Timestamp,
    'blobId' : IDL.Text,
    'detectionLogId' : IDL.Text,
  });
  const MissingPerson = IDL.Record({
    'id' : IDL.Text,
    'dateOfDisappearance' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'reportedBy' : IDL.Text,
    'isFound' : IDL.Bool,
    'ageAtDisappearance' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SystemStats = IDL.Record({
    'missingPersonsCount' : IDL.Nat,
    'totalCriminals' : IDL.Nat,
    'detectionsToday' : IDL.Nat,
    'activeAlerts' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCriminalProfile' : IDL.Func([CriminalProfile], [], []),
    'addDetectionLog' : IDL.Func([DetectionLog], [], []),
    'addEvidenceRecord' : IDL.Func([EvidenceRecord], [], []),
    'addMissingPerson' : IDL.Func([MissingPerson], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCriminalProfiles' : IDL.Func(
        [],
        [IDL.Vec(CriminalProfile)],
        ['query'],
      ),
    'getAllDetectionLogs' : IDL.Func([], [IDL.Vec(DetectionLog)], ['query']),
    'getAllEvidenceRecords' : IDL.Func(
        [],
        [IDL.Vec(EvidenceRecord)],
        ['query'],
      ),
    'getAllMissingPersons' : IDL.Func([], [IDL.Vec(MissingPerson)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCriminalProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CriminalProfile)],
        ['query'],
      ),
    'getEvidenceRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EvidenceRecord)],
        ['query'],
      ),
    'getMissingPerson' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MissingPerson)],
        ['query'],
      ),
    'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCriminalProfile' : IDL.Func([CriminalProfile], [], []),
    'updateMissingPerson' : IDL.Func([MissingPerson], [], []),
  });
};

export const init = ({ IDL }) => { return []; };