/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface EvidenceRecord {
    id: string;
    metadata: string;
    timestamp: Timestamp;
    blobId: string;
    detectionLogId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SystemStats {
    missingPersonsCount: bigint;
    totalCriminals: bigint;
    detectionsToday: bigint;
    activeAlerts: bigint;
}
export interface DetectionLog {
    id: string;
    activityLabel: string;
    threatLevel: ThreatLevel;
    detectedPersonName: string;
    matchPercentage: bigint;
    evidencePhotoUrl?: string;
    timestamp: Timestamp;
    location: string;
    weaponsDetected: Array<string>;
    cameraId: string;
    detectionType: DetectionType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CriminalProfile {
    id: string;
    age: bigint;
    criminalRecord: string;
    threatLevel: ThreatLevel;
    name: string;
    createdAt: Timestamp;
    photoUrl: string;
    nationality: string;
    isActive: boolean;
    gender: string;
    aliases: Array<string>;
}
export interface MissingPerson {
    id: string;
    dateOfDisappearance: Timestamp;
    name: string;
    createdAt: Timestamp;
    description: string;
    photoUrl: string;
    reportedBy: string;
    isFound: boolean;
    ageAtDisappearance: bigint;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DetectionType {
    missingPerson = "missingPerson",
    knownCriminal = "knownCriminal",
    unknownPerson = "unknownPerson"
}
export enum ThreatLevel {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCriminalProfile(profile: CriminalProfile): Promise<void>;
    addDetectionLog(log: DetectionLog): Promise<void>;
    addEvidenceRecord(record: EvidenceRecord): Promise<void>;
    addMissingPerson(person: MissingPerson): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllCriminalProfiles(): Promise<Array<CriminalProfile>>;
    getAllDetectionLogs(): Promise<Array<DetectionLog>>;
    getAllEvidenceRecords(): Promise<Array<EvidenceRecord>>;
    getAllMissingPersons(): Promise<Array<MissingPerson>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCriminalProfile(id: string): Promise<CriminalProfile | null>;
    getEvidenceRecord(id: string): Promise<EvidenceRecord | null>;
    getMissingPerson(id: string): Promise<MissingPerson | null>;
    getSystemStats(): Promise<SystemStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCriminalProfile(profile: CriminalProfile): Promise<void>;
    updateMissingPerson(person: MissingPerson): Promise<void>;
}
import type { CriminalProfile as _CriminalProfile, DetectionLog as _DetectionLog, DetectionType as _DetectionType, EvidenceRecord as _EvidenceRecord, MissingPerson as _MissingPerson, ThreatLevel as _ThreatLevel, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCriminalProfile(arg0: CriminalProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCriminalProfile(to_candid_CriminalProfile_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCriminalProfile(to_candid_CriminalProfile_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDetectionLog(arg0: DetectionLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDetectionLog(to_candid_DetectionLog_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDetectionLog(to_candid_DetectionLog_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEvidenceRecord(arg0: EvidenceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvidenceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvidenceRecord(arg0);
            return result;
        }
    }
    async addMissingPerson(arg0: MissingPerson): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMissingPerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMissingPerson(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllCriminalProfiles(): Promise<Array<CriminalProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCriminalProfiles();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCriminalProfiles();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDetectionLogs(): Promise<Array<DetectionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDetectionLogs();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDetectionLogs();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvidenceRecords(): Promise<Array<EvidenceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvidenceRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvidenceRecords();
            return result;
        }
    }
    async getAllMissingPersons(): Promise<Array<MissingPerson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMissingPersons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMissingPersons();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCriminalProfile(arg0: string): Promise<CriminalProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCriminalProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCriminalProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvidenceRecord(arg0: string): Promise<EvidenceRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceRecord(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceRecord(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMissingPerson(arg0: string): Promise<MissingPerson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMissingPerson(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMissingPerson(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemStats(): Promise<SystemStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCriminalProfile(arg0: CriminalProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCriminalProfile(to_candid_CriminalProfile_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCriminalProfile(to_candid_CriminalProfile_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMissingPerson(arg0: MissingPerson): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMissingPerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMissingPerson(arg0);
            return result;
        }
    }
}
function from_candid_CriminalProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CriminalProfile): CriminalProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DetectionLog_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DetectionLog): DetectionLog {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_DetectionType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DetectionType): DetectionType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatLevel_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatLevel): ThreatLevel {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CriminalProfile]): CriminalProfile | null {
    return value.length === 0 ? null : from_candid_CriminalProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EvidenceRecord]): EvidenceRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MissingPerson]): MissingPerson | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    criminalRecord: string;
    threatLevel: _ThreatLevel;
    name: string;
    createdAt: _Timestamp;
    photoUrl: string;
    nationality: string;
    isActive: boolean;
    gender: string;
    aliases: Array<string>;
}): {
    id: string;
    age: bigint;
    criminalRecord: string;
    threatLevel: ThreatLevel;
    name: string;
    createdAt: Timestamp;
    photoUrl: string;
    nationality: string;
    isActive: boolean;
    gender: string;
    aliases: Array<string>;
} {
    return {
        id: value.id,
        age: value.age,
        criminalRecord: value.criminalRecord,
        threatLevel: from_candid_ThreatLevel_n21(_uploadFile, _downloadFile, value.threatLevel),
        name: value.name,
        createdAt: value.createdAt,
        photoUrl: value.photoUrl,
        nationality: value.nationality,
        isActive: value.isActive,
        gender: value.gender,
        aliases: value.aliases
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    activityLabel: string;
    threatLevel: _ThreatLevel;
    detectedPersonName: string;
    matchPercentage: bigint;
    evidencePhotoUrl: [] | [string];
    timestamp: _Timestamp;
    location: string;
    weaponsDetected: Array<string>;
    cameraId: string;
    detectionType: _DetectionType;
}): {
    id: string;
    activityLabel: string;
    threatLevel: ThreatLevel;
    detectedPersonName: string;
    matchPercentage: bigint;
    evidencePhotoUrl?: string;
    timestamp: Timestamp;
    location: string;
    weaponsDetected: Array<string>;
    cameraId: string;
    detectionType: DetectionType;
} {
    return {
        id: value.id,
        activityLabel: value.activityLabel,
        threatLevel: from_candid_ThreatLevel_n21(_uploadFile, _downloadFile, value.threatLevel),
        detectedPersonName: value.detectedPersonName,
        matchPercentage: value.matchPercentage,
        evidencePhotoUrl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.evidencePhotoUrl)),
        timestamp: value.timestamp,
        location: value.location,
        weaponsDetected: value.weaponsDetected,
        cameraId: value.cameraId,
        detectionType: from_candid_DetectionType_n27(_uploadFile, _downloadFile, value.detectionType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): ThreatLevel {
    return "low" in value ? ThreatLevel.low : "high" in value ? ThreatLevel.high : "critical" in value ? ThreatLevel.critical : "medium" in value ? ThreatLevel.medium : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    missingPerson: null;
} | {
    knownCriminal: null;
} | {
    unknownPerson: null;
}): DetectionType {
    return "missingPerson" in value ? DetectionType.missingPerson : "knownCriminal" in value ? DetectionType.knownCriminal : "unknownPerson" in value ? DetectionType.unknownPerson : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CriminalProfile>): Array<CriminalProfile> {
    return value.map((x)=>from_candid_CriminalProfile_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DetectionLog>): Array<DetectionLog> {
    return value.map((x)=>from_candid_DetectionLog_n24(_uploadFile, _downloadFile, x));
}
function to_candid_CriminalProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CriminalProfile): _CriminalProfile {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_DetectionLog_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DetectionLog): _DetectionLog {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_DetectionType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DetectionType): _DetectionType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ThreatLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatLevel): _ThreatLevel {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    activityLabel: string;
    threatLevel: ThreatLevel;
    detectedPersonName: string;
    matchPercentage: bigint;
    evidencePhotoUrl?: string;
    timestamp: Timestamp;
    location: string;
    weaponsDetected: Array<string>;
    cameraId: string;
    detectionType: DetectionType;
}): {
    id: string;
    activityLabel: string;
    threatLevel: _ThreatLevel;
    detectedPersonName: string;
    matchPercentage: bigint;
    evidencePhotoUrl: [] | [string];
    timestamp: _Timestamp;
    location: string;
    weaponsDetected: Array<string>;
    cameraId: string;
    detectionType: _DetectionType;
} {
    return {
        id: value.id,
        activityLabel: value.activityLabel,
        threatLevel: to_candid_ThreatLevel_n10(_uploadFile, _downloadFile, value.threatLevel),
        detectedPersonName: value.detectedPersonName,
        matchPercentage: value.matchPercentage,
        evidencePhotoUrl: value.evidencePhotoUrl ? candid_some(value.evidencePhotoUrl) : candid_none(),
        timestamp: value.timestamp,
        location: value.location,
        weaponsDetected: value.weaponsDetected,
        cameraId: value.cameraId,
        detectionType: to_candid_DetectionType_n14(_uploadFile, _downloadFile, value.detectionType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    criminalRecord: string;
    threatLevel: ThreatLevel;
    name: string;
    createdAt: Timestamp;
    photoUrl: string;
    nationality: string;
    isActive: boolean;
    gender: string;
    aliases: Array<string>;
}): {
    id: string;
    age: bigint;
    criminalRecord: string;
    threatLevel: _ThreatLevel;
    name: string;
    createdAt: _Timestamp;
    photoUrl: string;
    nationality: string;
    isActive: boolean;
    gender: string;
    aliases: Array<string>;
} {
    return {
        id: value.id,
        age: value.age,
        criminalRecord: value.criminalRecord,
        threatLevel: to_candid_ThreatLevel_n10(_uploadFile, _downloadFile, value.threatLevel),
        name: value.name,
        createdAt: value.createdAt,
        photoUrl: value.photoUrl,
        nationality: value.nationality,
        isActive: value.isActive,
        gender: value.gender,
        aliases: value.aliases
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatLevel): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == ThreatLevel.low ? {
        low: null
    } : value == ThreatLevel.high ? {
        high: null
    } : value == ThreatLevel.critical ? {
        critical: null
    } : value == ThreatLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DetectionType): {
    missingPerson: null;
} | {
    knownCriminal: null;
} | {
    unknownPerson: null;
} {
    return value == DetectionType.missingPerson ? {
        missingPerson: null
    } : value == DetectionType.knownCriminal ? {
        knownCriminal: null
    } : value == DetectionType.unknownPerson ? {
        unknownPerson: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
